theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true

params:
  summary:
    position: hero
  breadcrumb:
    position: none
  posts:
    index:
      truncate_description: 0
      layout: grid
  search:
    active: true
  debug:
     productionUrl: "https://publications.arnaudlevy.com"
