theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
summaryLength: 20

languages:
  fr:
    permalinks:
      page:
        watch_posts: "veille/:year-:month-:day-:slug/"
      section:
        watch_posts: "veille"

params:
  plausible: publications.arnaudlevy.com
  summary:
    position: hero
  breadcrumb:
    position: none
  posts:
    index:
      truncate_description: 0
      layout: grid
  search:
    active: true
  debug:
     productionUrl: "https://publications.arnaudlevy.com"
